---
- name: Deploy UserInfoApp Frontend
  hosts: all
  become: yes
  tasks:
     - name: Update system packages
       yum:
          name: "*"
          state: latest

     - name: Install NGINX and Git
       yum:
          name:
             - nginx
             - git
          state: present

     - name: Clone UserInfoApp repository
       git:
          repo: https://github.com/hemanthtadikonda/UserInfoApp.git
          dest: /home/centos/UserInfoApp

     - name: Remove existing NGINX HTML files
       command: rm -rf /usr/share/nginx/html/*

     - name: Copy index.html to NGINX HTML directory
       copy:
          src: /home/centos/UserInfoApp/frontend/index.html
          dest: /usr/share/nginx/html/index.html

     - name: Copy NGINX app configuration file
       template:
          src: /home/centos/UserInfoApp/frontend/templates/app.conf
          dest: /etc/nginx/conf.d/app.conf
       notify: Validate NGINX Configuration

     - name: Ensure NGINX log directory permissions
       file:
          path: /var/log/nginx
          state: directory
          owner: nginx
          group: nginx
          mode: '0755'

     - name: Ensure NGINX run directory permissions
       file:
          path: /run
          state: directory
          owner: nginx
          group: nginx
          mode: '0755'

     - name: Reload systemd daemon
       systemd:
          daemon_reload: yes

     - name: Enable and restart NGINX service
       systemd:
          name: nginx
          enabled: yes
          state: restarted

