---
- name: Deploy UserInfoApp Backend
  hosts: all
  become: yes
  tasks:
     - name: Install Python 3 and pip
       yum:
          name:
             - python3
             - python3-pip
          state: present

     - name: Install Git
       yum:
          name: git
          state: present

     - name: Clone UserInfoApp repository
       git:
          repo: https://github.com/hemanthtadikonda/UserInfoApp.git
          dest: /home/ec2-user/UserInfoApp

     - name: Install required Python packages
       pip:
          requirements: /home/ec2-user/UserInfoApp/backend/requirements.txt
          state: present
          executable: pip3

     - name: Copy backend service file
       copy:
          src: /home/ec2-user/UserInfoApp/backend/service/backend.service
          dest: /etc/systemd/system/backend.service
          mode: '0644'

     - name: Reload systemd daemon
       systemd:
          daemon_reload: yes

     - name: Enable and restart backend service
       systemd:
          name: backend
          enabled: yes
          state: restarted
